---

  - name: Edit /etc/kubernetes/config
    copy: src=node-config/kube-node-config dest=/etc/kubernetes/config

  - name: Edit the /etc/kuberenetes/kubelet
    copy: src=node-config/kubelet dest=/etc/kubernetes/kubelet
    
  - name: modify kubelet
    script: node-config/host.sh

  - name: Edit the /etc/kubernetes/proxy
    copy: src=node-config/proxy dest=/etc/kubernetes/proxy
